 name: Build and Push to ECR

 on:
   push:
     branches:
       - main

 jobs:
   build-push:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}

       - name: Login to Amazon ECR
         run: |
           aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 387132115905.dkr.ecr.us-east-1.amazonaws.com

       - name: Build, tag, and push image to Amazon ECR
         run: |
           docker build -t mediplus:v2 .
           docker tag mediplus:v2 387132115905.dkr.ecr.us-east-1.amazonaws.com/mediplus:v2
           docker push 387132115905.dkr.ecr.us-east-1.amazonaws.com/mediplus:v2

   deploy:
     runs-on: ubuntu-latest
     needs: build-push
     steps:
       - name: Check my ssh key
         run: |
           echo "${{ secrets.SSH_KEY }}" > sshkey.pem
           chmod 600 sshkey.pem
           cat sshkey.pem

           ssh -o StrictHostKeyChecking=no -i sshkey.pem ubuntu@107.21.24.212 "docker pull 387132115905.dkr.ecr.us-east-1.amazonaws.com/mediplus:v2"

                      ssh -o StrictHostKeyChecking=no -i sshkey.pem ubuntu@107.21.24.212 "docker rm -f mediplus"

           ssh -o StrictHostKeyChecking=no -i sshkey.pem ubuntu@107.21.24.212 "docker run -d --name mediplus -p 80:80 387132115905.dkr.ecr.us-east-1.amazonaws.com/mediplus:v2"